config/routes.rb
Dooraccess::Application.routes.draw do
  match 'ipns/import' => 'ipns#import', :as => :import_ipn
  resources :ipns
  match 'ipns/:id/link' => 'ipns#link', :as => :link_ipn
  match 'ipns/:id/validate' => 'ipns#validate', :as => :validate_ipn

  resources :paypal_csvs
  match 'paypal_csvs/:id/link' => 'paypal_csvs#link', :as => :link_paypal_csv

  resources :payments
  resources :resources
  resources :resource_categories, except: :show

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/mac_log' => 'statistics#mac_log', :as => :mac_statistics
  match 'statistics/door_log' => 'statistics#door_log', :as => :door_statistics

  resources :user_certifications

  resources :certifications

  resources :contracts
  match 'contracts/find_for_user/:user_id' => 'contracts#find_for_user', as: 'find_for_user'

  devise_for :users, :skip => :registrations
  devise_scope :user do
    resource :registration,
      :only => [:new, :create, :edit, :update],
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
        get :cancel
      end
  end

  match 'user_summary/:id' => 'users#user_summary' # User summary view
  match 'users/activity' => 'users#activity' # User activity
  match 'users/new_member_report' => 'users#new_member_report' # New member report (For emailing)
  match 'users/merge' => 'users#merge_view', :via => :get # Merge view
  match 'users/merge' => 'users#merge_action', :via => :post # Merge action
  match 'users/inactive' => 'users#inactive' # Inactive users report
  resources :users do 
    get 'email' => 'users#compose_email', :as => "compose_email"
    post 'email' => 'users#send_email'
    resources 'contracts', only: [:index]
  end
  match 'users/create' => 'users#create', :via => :post  # Use POST users/create instead of POST users to avoid devise conflict

  match 'cards/upload_all' => 'cards#upload_all', :as => :upload_all
  match 'cards/authorize/:id' => 'cards#authorize', :as => :authorize
  resources :cards
  match 'cards/:id/upload' => 'cards#upload', :as => :upload

  match 'space_api' => 'space_api#index', :as => :space_api
  match 'space_api/simple(.format)' => 'space_api#simple', :as => :space_api_simple
  match 'space_api/alert_if_not/:status' => 'space_api#alert_if_not_status', :via => :get, :as => :space_api_alert_if_not_status
  match 'space_api/access' => 'space_api#access', :via => :get, :as => :space_api_access
  match 'space_api/access' => 'space_api#access_post', :via => :post

  match 'door_logs' => 'door_logs#index', :as => :door_logs
  match 'door_logs/download' => 'door_logs#download', :as => :download
  match 'door_logs/auto_download' => 'door_logs#auto_download', :as => :auto_download

  match 'macs/scan' => 'macs#scan'
  match 'macs/import' => 'macs#import'
  match 'macs/history' => 'macs#history'
  resources :macs
  resources :mac_logs

  resources :settings, :only => [:index, :edit, :update]

  match 'more_info' => 'home#more_info'
  root :to => "home#index"

end

app/models/certification.rb
class Certification < ActiveRecord::Base
  attr_accessible :description, :name, :slug
  has_many :user_certifications
  has_many :users, :through => :user_certifications

  validates_presence_of :name, :slug
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  load_and_authorize_resource :certification
  #load_and_authorize_resource :user, :through => :certification
  before_filter :authenticate_user!

  # GET /certifications
  # GET /certifications.json
  def index
    @certifications = @certifications.sort_by(&:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @certifications }
    end
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
    @certification_users = []

    #TODO: make a better SQL query for this
    @certification.users.sort_by(&:name).each do |user|
      @certification_users.push user if can? :read, user
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @certification }
    end
  end

  # GET /certifications/new
  # GET /certifications/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @certification }
    end
  end

  # GET /certifications/1/edit
  def edit
  end

  # POST /certifications
  # POST /certifications.json
  def create
    respond_to do |format|
      if @certification.save
        format.html { redirect_to Certification, :notice => 'Certification was successfully created.' }
        format.json { render :json => @certification, :status => :created, :location => @certification }
      else
        format.html { render :action => "new" }
        format.json { render :json => @certification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /certifications/1
  # PUT /certifications/1.json
  def update
    respond_to do |format|
      if @certification.update_attributes(params[:certification])
        format.html { redirect_to Certification, :notice => 'Certification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @certification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.json
  def destroy
    @certification.destroy

    respond_to do |format|
      format.html { redirect_to certifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/views/certifications/_form.html.erb
<%= form_for(@certification) do |f| %>
  <% if @certification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certification.errors.count, "error") %> prohibited this certification from being saved:</h2>

      <ul>
      <% @certification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug, "Slug (lowercase, single-word identifier)" %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certifications/edit.html.erb
<h1>Editing certification</h1>

<%= render 'form' %>

<%= link_to 'Show', @certification %> |
<%= link_to 'Back', certifications_path %>

app/views/certifications/index.html.erb
<h1>Certification Classes</h1>

<%= link_to 'Create Certification', new_certification_path if can? :create, Certification %> 

<ul>
<% @certifications.each do |certification| %>
  <li><%= link_to certification.name, certification %>
  (<%= certification.slug %>)
  <% if can? :update, certification %> | <%= link_to 'Edit', edit_certification_path(certification) %><% end %>
  <% if can? :destroy, certification %> | <%= link_to 'Destroy', certification, :confirm => 'Are you sure?', :method => :delete %><% end %>
  </li>
<% end %>
</ul>

<br />

app/views/certifications/new.html.erb
<h1>New certification</h1>

<%= render 'form' %>

<%= link_to 'Back', certifications_path %>

app/views/certifications/show.html.erb
<p>
  <b>Name:</b>
  <%= @certification.name %>
</p>

<p>
  <b>Slug (lowercase, single-word identifier):</b>
  <%= @certification.slug %>
</p>

<p>
  <b>Description:</b>
  <%= simple_format @certification.description %>
</p>

<p>
  <b>Certified Users:</b>
  <%= link_to "Click Here", user_certifications_path %>
</p>

<% if can? :update, @certification %><%= link_to 'Edit', edit_certification_path(@certification) %> |<% end %>
<%= link_to 'Back', certifications_path %>