config/routes.rb
Dooraccess::Application.routes.draw do
  match 'ipns/import' => 'ipns#import', :as => :import_ipn
  resources :ipns
  match 'ipns/:id/link' => 'ipns#link', :as => :link_ipn
  match 'ipns/:id/validate' => 'ipns#validate', :as => :validate_ipn

  resources :paypal_csvs
  match 'paypal_csvs/:id/link' => 'paypal_csvs#link', :as => :link_paypal_csv

  resources :payments
  resources :resources
  resources :resource_categories, except: :show

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/mac_log' => 'statistics#mac_log', :as => :mac_statistics
  match 'statistics/door_log' => 'statistics#door_log', :as => :door_statistics

  resources :user_certifications

  resources :certifications

  resources :contracts
  match 'contracts/find_for_user/:user_id' => 'contracts#find_for_user', as: 'find_for_user'

  devise_for :users, :skip => :registrations
  devise_scope :user do
    resource :registration,
      :only => [:new, :create, :edit, :update],
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
        get :cancel
      end
  end

  match 'user_summary/:id' => 'users#user_summary' # User summary view
  match 'users/activity' => 'users#activity' # User activity
  match 'users/new_member_report' => 'users#new_member_report' # New member report (For emailing)
  match 'users/merge' => 'users#merge_view', :via => :get # Merge view
  match 'users/merge' => 'users#merge_action', :via => :post # Merge action
  match 'users/inactive' => 'users#inactive' # Inactive users report
  resources :users do 
    get 'email' => 'users#compose_email', :as => "compose_email"
    post 'email' => 'users#send_email'
    resources 'contracts', only: [:index]
  end
  match 'users/create' => 'users#create', :via => :post  # Use POST users/create instead of POST users to avoid devise conflict

  match 'cards/upload_all' => 'cards#upload_all', :as => :upload_all
  match 'cards/authorize/:id' => 'cards#authorize', :as => :authorize
  resources :cards
  match 'cards/:id/upload' => 'cards#upload', :as => :upload

  match 'space_api' => 'space_api#index', :as => :space_api
  match 'space_api/simple(.format)' => 'space_api#simple', :as => :space_api_simple
  match 'space_api/alert_if_not/:status' => 'space_api#alert_if_not_status', :via => :get, :as => :space_api_alert_if_not_status
  match 'space_api/access' => 'space_api#access', :via => :get, :as => :space_api_access
  match 'space_api/access' => 'space_api#access_post', :via => :post

  match 'door_logs' => 'door_logs#index', :as => :door_logs
  match 'door_logs/download' => 'door_logs#download', :as => :download
  match 'door_logs/auto_download' => 'door_logs#auto_download', :as => :auto_download

  match 'macs/scan' => 'macs#scan'
  match 'macs/import' => 'macs#import'
  match 'macs/history' => 'macs#history'
  resources :macs
  resources :mac_logs

  resources :settings, :only => [:index, :edit, :update]

  match 'more_info' => 'home#more_info'
  root :to => "home#index"

end

app/views/resources/_form.html.erb
<%= form_for @resource, :html => { :multipart => true, class: "col-sm-6" } do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :resource_category_id, "Category" %><br />
    <%= select(:resource, :resource_category_id, options_from_collection_for_select(ResourceCategory.all.sort_by(&:name), :id, :name, @resource.resource_category_id ), {}, {class: "form-control"} ) %>
  </p>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </p>
  <p>
    <%= f.label :serial, "Serial" %>
    <br />
    <%= f.text_field :serial, class: "form-control" %>
  </p>
  <p>
    <%= f.label :specs, "Specs" %>
    <br/>
    <%= f.text_field :specs, class: "form-control" %>
  </p>
  <p>
    <%= f.label :status, "Status/Location" %>
    <br/>
    <%= f.text_field :status, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label :disposed_at, "Disposed?" %><br />
    <%= f.date_select :disposed_at, include_blank: true %>
  </p>

    <p>
      <%= f.label :user_id, "Owner" %>
      <br />
      <%= select(:resource, :user_id, options_from_collection_for_select(@users, :id, :name, @resource.user_id), {include_blank: true}, {class: "form-control"}) %>
    </p>

  <p>
    <%= f.label :donatable %><br />
    <%= f.check_box :donatable %>
  </p>

  <p>
    <%= f.label :estimated_value, "Estimated Value" %><br />
    <%= f.text_field :estimated_value, class: "form-control" %>
  </p>

  <% [:picture, :picture2, :picture3, :picture4].each do |p| %>
    <p class="row">
      <span class="col-sm-3">
        <%= f.label p %><br />
        <%= f.file_field p %>
      </span>
      <span class="col-sm-2">
        <%= link_to image_tag(@resource.send(p).url(:tiny)), @resource.send(p).url unless @resource.send(p).blank? %>
      </span>
    </p>				      
  <% end %>

  <p>
    <%= f.label :notes %><br />
    <%= f.text_area :notes, class: "form-control" %>
  </p>
  <p>
    <%= f.submit nil, class: "btn btn-primary" %>
  </p>
<% end %>

app/views/resources/_resource.html.erb
<div class="resource">
  <div class="thumbnail">
    <%= link_to(resource) do %>
      <% if resource.user %>
        <span class="ownership">Owned by:<br/><%= resource.user.name %></span>
      <% end %>
      <% if resource.disposed_at %>
        <span class="disposed">Disposed:<br/><%= resource.disposed_at.to_date %></span>
      <% end %>
      <%= image_tag(resource.picture.url(:thumb)) if resource.picture? %>
      <h4><%=h resource.name %></h4>
    <% end %>
  </div>
</div>

app/views/resources/edit.html.erb
<h1>Edit Resource
<%= link_to 'Back', resources_path, class: "btn btn-default" %>
</h1>
<%= render 'form' %>

app/views/resources/index.html.erb
<div class="row">
  <h1 class="col-md-8">Lab Resources
    <%= link_to 'Add Resource', new_resource_path, :class => "btn btn-success" if can? :create, Resource %>
    <%= link_to 'Categories', resource_categories_path, :class => "btn btn-primary" if can? :read, ResourceCategory %>
    <a class="btn btn-default" onclick="$('#accordion .collapse').collapse('toggle')" />Expand/Collapse All</a>
  </h1>
  
  <span class="col-md-2 col-xs-6">
    <h3>Featured item:</h3>
    <%= render @featured_resource unless @featured_resource.blank? %>
  </span>
</div>

<div class="row">
<% unless @resources.blank? %>
  <div class="panel-group col-sm-8" id="accordion">
    <% @resources.sort_by{|r| [r.resource_category_name,r.name] }.group_by(&:resource_category).each do |resource_category,resources| %>
    <div class="panel panel-default">
      <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapse_cat_<%= resource_category.id %>">
        <h4 class="panel-title">
            <%= resource_category.name %>
        </h4>
      </div>
      <div id="collapse_cat_<%= resource_category.id %>" class="panel-collapse collapse">
        <div class="panel-body">
          <% resources.each do |resource| %>
            <div class="col-xs-2">
              <%= render resource %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
<% end %>
</div>

<br />

app/views/resources/new.html.erb
<h1>New Resource
<%= link_to 'Back', resources_path, class: "btn btn-default" %>
</h1>
<%= render 'form' %>

app/views/resources/show.html.erb
<div class="row">
  <div class="thumbnail" style="width: 300px">
    <div class="row">
      <div class="col-xs-12">
        <%= link_to image_tag(@resource.picture.url(:medium), height: 300, width: 300), @resource.picture.url if @resource.picture? %>
      </div>
    </div>
    <div class="row">
      <% [:picture2, :picture3, :picture4].each do |p| %>
        <% unless @resource.send(p).blank? %>
          <div class="col-xs-4">
            <%= link_to image_tag(@resource.send(p).url(:thumb)), @resource.send(p).url %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<h2><%=h @resource.name %>
<%= link_to 'Back', resources_path, class: "btn btn-default" %>
<%= link_to 'Edit', edit_resource_path(@resource), class: "btn btn-primary" if can? :edit, @resource %>
</h2>
<% if @resource.user || @resource.owner %>
<p>
  <b>Owner:</b>
  <%=h (@resource.user || @resource.owner).name %>
</p>
<% end %>
<p>
  <b>Category:</b>
  <%=h @resource.resource_category.name if @resource.resource_category %>
</p>

<p>
  <b>Serial:</b>
  <%=h @resource.serial %>
</p>

<p>
  <b>Specs:</b>
  <%=h @resource.specs %>
</p>

<p>
  <b>Status/Location:</b>
  <%=h @resource.status %>

  <% if @resource.disposed_at %>
    <b>Disposed:</b>
    <%=h @resource.disposed_at.to_date %>
  <% end %>
</p>

<p>
  <b>Donatable:</b>
  <%=h @resource.donatable %>
</p>

<p>
  <b>Estimated Value:</b>
  <%=h @resource.estimated_value %>
</p>

<p>
  <b>Notes:</b>
  <div class="row">
    <div class="col-sm-6">
      <%= simple_format @resource.notes %>
    </div>
  </div>
</p>

<%= link_to 'Delete', resource_path(@resource), {:confirm => 'Are you sure you want to delete this forever?', :method => :delete, :class => "btn btn-danger"} if can? :destroy, @resource %>