config/routes.rb
Dooraccess::Application.routes.draw do
  match 'ipns/import' => 'ipns#import', :as => :import_ipn
  resources :ipns
  match 'ipns/:id/link' => 'ipns#link', :as => :link_ipn
  match 'ipns/:id/validate' => 'ipns#validate', :as => :validate_ipn

  resources :paypal_csvs
  match 'paypal_csvs/:id/link' => 'paypal_csvs#link', :as => :link_paypal_csv

  resources :payments
  resources :resources
  resources :resource_categories, except: :show

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/mac_log' => 'statistics#mac_log', :as => :mac_statistics
  match 'statistics/door_log' => 'statistics#door_log', :as => :door_statistics

  resources :user_certifications

  resources :certifications

  resources :contracts
  match 'contracts/find_for_user/:user_id' => 'contracts#find_for_user', as: 'find_for_user'

  devise_for :users, :skip => :registrations
  devise_scope :user do
    resource :registration,
      :only => [:new, :create, :edit, :update],
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
        get :cancel
      end
  end

  match 'user_summary/:id' => 'users#user_summary' # User summary view
  match 'users/activity' => 'users#activity' # User activity
  match 'users/new_member_report' => 'users#new_member_report' # New member report (For emailing)
  match 'users/merge' => 'users#merge_view', :via => :get # Merge view
  match 'users/merge' => 'users#merge_action', :via => :post # Merge action
  match 'users/inactive' => 'users#inactive' # Inactive users report
  resources :users do 
    get 'email' => 'users#compose_email', :as => "compose_email"
    post 'email' => 'users#send_email'
    resources 'contracts', only: [:index]
  end
  match 'users/create' => 'users#create', :via => :post  # Use POST users/create instead of POST users to avoid devise conflict

  match 'cards/upload_all' => 'cards#upload_all', :as => :upload_all
  match 'cards/authorize/:id' => 'cards#authorize', :as => :authorize
  resources :cards
  match 'cards/:id/upload' => 'cards#upload', :as => :upload

  match 'space_api' => 'space_api#index', :as => :space_api
  match 'space_api/simple(.format)' => 'space_api#simple', :as => :space_api_simple
  match 'space_api/alert_if_not/:status' => 'space_api#alert_if_not_status', :via => :get, :as => :space_api_alert_if_not_status
  match 'space_api/access' => 'space_api#access', :via => :get, :as => :space_api_access
  match 'space_api/access' => 'space_api#access_post', :via => :post

  match 'door_logs' => 'door_logs#index', :as => :door_logs
  match 'door_logs/download' => 'door_logs#download', :as => :download
  match 'door_logs/auto_download' => 'door_logs#auto_download', :as => :auto_download

  match 'macs/scan' => 'macs#scan'
  match 'macs/import' => 'macs#import'
  match 'macs/history' => 'macs#history'
  resources :macs
  resources :mac_logs

  resources :settings, :only => [:index, :edit, :update]

  match 'more_info' => 'home#more_info'
  root :to => "home#index"

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  has_one :ipn
  has_one :paypal_csv
  attr_accessible :date, :user_id, :created_by, :amount

  validates_presence_of :user_id, :date, :amount # not created_by
  validates_uniqueness_of :date, :scope => :user_id, :message => ' of payment already exists for this user.' 

  def human_date
    if date.year < DateTime.now.year
      date.strftime("%b %e, %y")
    else
      date.strftime("%b %e")
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource :payment
  #load_and_authorize_resource :user, :through => :payment
  before_filter :authenticate_user!

  # Load users and certs based on current ability
  before_filter do
    @users = User.where(:hidden => false).where("member_level > 10").accessible_by(current_ability).sort_by(&:name_with_payee_and_member_level)
  end

  before_filter :only => [:create, :update] do
    @payment.created_by = current_user.id
  end

  # GET /payments
  # GET /payments.json
  def index
    @payments = @payments.order("date DESC")
    @graph = { :members => chart("members"), 
      :total => chart("total"), 
      :basic => chart("basic"), 
      :associate => chart("associate")}

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @payments }
    end
  end

  # Private method for index charts
  def chart name
    chart_name = name || "total"
    if chart_name == "total"
      chart_type = [25, 50, 100]
    elsif chart_name == "members"
      chart_type = [25, 50, 100]
    elsif chart_name == "basic"
      chart_type = [50]
    elsif chart_name == "associate"
      chart_type = [25]
    else
      chart_type = [] 
    end

    payment_months = @payments.sort_by(&:date).group_by{ |p| p.date.beginning_of_month }
    @payments_by_month = []
    payment_months.each do |month|
      # Calculate sum of amounts for each month and store at end of month array
      @payments_by_month << [month.first.to_time.to_i*1000, month.last.sum{|p| 
        amount = amount_or_level(p)
        if chart_type.include?(amount)
          if chart_name == "members"
            1 # Output 1 to count members
          else
            amount # Output dollars to count amount
          end
        else
          0
        end
      }]
    end

    return @payments_by_month
  end

  def amount_or_level p
    if p.amount
      return p.amount.to_i
    else
      if p.user
        Rails.logger.info p.user.member_level
        return p.user.member_level.to_i
      else
        Rails.logger.info p.inspect
        Rails.logger.info p.user.inspect
        return 0
      end
    end 
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @payment }
    end
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    Rails.logger.warn "payment:"
    Rails.logger.warn @payment.inspect
    respond_to do |format|
      if @payment.save
        format.html { redirect_to payments_url, :notice => 'Payment was successfully created.' }
        format.json { render :json => @payment, :status => :created, :location => @payment }
      else
        format.html { render :action => "new" }
        format.json { render :json => @payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to payments_url, :notice => 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @payment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id, "User" %><br />
    <%= collection_select(:payment, :user_id, @users, :id, :name_with_payee_and_member_level) %> (inactive members are not shown.)
  </div>
  <div class="field">
    <%= f.label :date, "Paid for month beginning" %><br />
    <%= f.date_select :date, :default => (DateTime.now - 1.month) %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="https://code.highcharts.com/highcharts.js"></script>
<script type="text/javascript">
$(function() {

  $( "#graph" ).dialog({
    autoOpen: false,
    height: 480,
    width: 640,
    modal: true,
  });
  $( "#graph-button" ).click(function() {
    $( "#graph" ).dialog( "open" );
  });

  $('#graph').highcharts({
      chart: {
          type: 'area',
          zoomType : 'x',
          resetZoomButton : {
            position: {
              align: 'left'
            }
          },
      },
      title: { 
        style : { fontSize: '12px' },
        text: "Numbers for Most Recent Month Greater Than They Appear" 
      },
      subtitle: { 
        style : { fontSize: '10px' },
        text: "Click and Drag to Zoom." 
      },
      xAxis: {
          type: 'datetime'
      },
      yAxis : [{ // Primary yAxis
        title : {
          text: "Income"
        },
        labels: {
          format: '${value}'
        }
      }, { // Secondary yAxis
        title : {
          text: "Members",
          style: { color: '#8bbc21' }
        },
        labels: {
          format: '{value}',
          style: { color: '#8bbc21' }
        },
        opposite: true
      }],
      tooltip: {
          shared: true,
          xDateFormat: '%B %Y',
          formatter: function() {
            console.log(this);
            output = '<b>'+ Highcharts.dateFormat(this.points[0].series.tooltipOptions.xDateFormat,this.x) +'</b><br/>';
            total = 0;
            this.points.forEach(function(e,i,a){
              console.log(e);
              output += '<span style="color:'+e.series.color+'">'+e.series.name +'</span>: '+ (e.series.tooltipOptions.valuePrefix||"") + Highcharts.numberFormat(e.y,0,".",",") +'<br/>';
              if(i < 2){
                total += e.y;
              }
            });
            output += '<b>Total:</b> '+(this.points[0].series.tooltipOptions.valuePrefix||"")+ Highcharts.numberFormat(total,0,".",",");
            return output;
          }
      },
      plotOptions: {
          area: {
              stacking: 'normal',
              lineColor: '#666666',
              lineWidth: 1,
              marker: {
                  lineWidth: 1,
                  lineColor: '#666666'
              }
          }
      },
      series: [{
        name: 'Basic',
        data: <%= @graph[:basic].to_json %>,
        tooltip: {
          valuePrefix: '$'
        }
      }, {
        name: 'Associate',
        data: <%= @graph[:associate].to_json %>,
        tooltip: {
          valuePrefix: '$'
        }
      }, {
        yAxis: 1,
        type: 'spline',
        name: 'Members',
        data: <%= @graph[:members].to_json %>
      }]
  });
    

});
</script>

<div id="graph" title="Payments by Month" style="height: 400px; width: 600px; float: right;"></div>


<h1>Listing payments <button id="graph-button" class="btn">View Graph</button></h1>

<p>
<b>Create Payments:</b>
<%= link_to 'Manually', new_payment_path %> |
<%= link_to 'Batched CSV', paypal_csvs_path %> |
<%= link_to 'IPN', ipns_path %>
</p>


<table>
  <tr>
    <th>Payee</th>
    <th>User</th>
    <th>Member level</th>
    <th>Last Payment</th>
    <th>Amount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.user.payee unless payment.user.blank? %></td>
    <td><%= link_to payment.user.name, payment.user unless payment.user.blank? %></td>
    <td><%= payment.user.member_level_string unless payment.user.blank? %></td>
    <td><%= payment.date %></td>
    <td><%= payment.amount %></td>
    <td><%= link_to 'Details', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
  </tr>
<% end %>
</table>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p>
  <b>User:</b>
  <%= link_to @payment.user.name_with_payee_and_member_level, @payment.user unless @payment.user.blank? %>
</p>

<p>
  <b>Paid for month beginning:</b>
  <%= @payment.date %>
</p>

<p>
  <b>Amount:</b>
  <%= @payment.amount %>
</p>

<p>
  <b>Last Modified by:</b>
  <% user = @users.find{|u| u.id == @payment.created_by} %>
  <% if user.blank? %>
    n/a
  <% else %>
    <%= link_to user.name, user %>
  <% end %>
</p>

<p>
  <b>Created date:</b>
  <%= @payment.created_at %>
</p>

<p>
  <b>Updated date:</b>
  <%= @payment.updated_at %>
</p>

<% if @payment.ipn.present? %>
  <p>
    <%= link_to "Paid via PayPal (IPN)", @payment.ipn %>
  </p>
<% end %>
<% if @payment.paypal_csv.present? %>
  <p>
    <%= link_to "Paid via PayPal (CSV)", @payment.paypal_csv %>
  </p>
<% end %>



<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Destroy', @payment, :confirm => 'Are you sure you want to destroy this payment?', :method => :delete if can? :destroy, @payment %> | 
<%= link_to 'Back', payments_path %>