config/routes.rb
Dooraccess::Application.routes.draw do
  match 'ipns/import' => 'ipns#import', :as => :import_ipn
  resources :ipns
  match 'ipns/:id/link' => 'ipns#link', :as => :link_ipn
  match 'ipns/:id/validate' => 'ipns#validate', :as => :validate_ipn

  resources :paypal_csvs
  match 'paypal_csvs/:id/link' => 'paypal_csvs#link', :as => :link_paypal_csv

  resources :payments
  resources :resources
  resources :resource_categories, except: :show

  match 'statistics' => 'statistics#index', :as => :statistics
  match 'statistics/mac_log' => 'statistics#mac_log', :as => :mac_statistics
  match 'statistics/door_log' => 'statistics#door_log', :as => :door_statistics

  resources :user_certifications

  resources :certifications

  resources :contracts
  match 'contracts/find_for_user/:user_id' => 'contracts#find_for_user', as: 'find_for_user'

  devise_for :users, :skip => :registrations
  devise_scope :user do
    resource :registration,
      :only => [:new, :create, :edit, :update],
      :path => 'users',
      :path_names => { :new => 'sign_up' },
      :controller => 'registrations',
      :as => :user_registration do
        get :cancel
      end
  end

  match 'user_summary/:id' => 'users#user_summary' # User summary view
  match 'users/activity' => 'users#activity' # User activity
  match 'users/new_member_report' => 'users#new_member_report' # New member report (For emailing)
  match 'users/merge' => 'users#merge_view', :via => :get # Merge view
  match 'users/merge' => 'users#merge_action', :via => :post # Merge action
  match 'users/inactive' => 'users#inactive' # Inactive users report
  resources :users do 
    get 'email' => 'users#compose_email', :as => "compose_email"
    post 'email' => 'users#send_email'
    resources 'contracts', only: [:index]
  end
  match 'users/create' => 'users#create', :via => :post  # Use POST users/create instead of POST users to avoid devise conflict

  match 'cards/upload_all' => 'cards#upload_all', :as => :upload_all
  match 'cards/authorize/:id' => 'cards#authorize', :as => :authorize
  resources :cards
  match 'cards/:id/upload' => 'cards#upload', :as => :upload

  match 'space_api' => 'space_api#index', :as => :space_api
  match 'space_api/simple(.format)' => 'space_api#simple', :as => :space_api_simple
  match 'space_api/alert_if_not/:status' => 'space_api#alert_if_not_status', :via => :get, :as => :space_api_alert_if_not_status
  match 'space_api/access' => 'space_api#access', :via => :get, :as => :space_api_access
  match 'space_api/access' => 'space_api#access_post', :via => :post

  match 'door_logs' => 'door_logs#index', :as => :door_logs
  match 'door_logs/download' => 'door_logs#download', :as => :download
  match 'door_logs/auto_download' => 'door_logs#auto_download', :as => :auto_download

  match 'macs/scan' => 'macs#scan'
  match 'macs/import' => 'macs#import'
  match 'macs/history' => 'macs#history'
  resources :macs
  resources :mac_logs

  resources :settings, :only => [:index, :edit, :update]

  match 'more_info' => 'home#more_info'
  root :to => "home#index"

end

app/models/card.rb
class Card < ActiveRecord::Base
  require 'open-uri'

  attr_accessible :id, :user_id, :name, :card_number, :card_permissions
  validates_presence_of :user_id, :card_number, :card_permissions
  validates_uniqueness_of :id, :card_number
  belongs_to :user

  def upload_to_door
    # load config values
    door_access_url = APP_CONFIG['door_access_url']
    door_access_password = APP_CONFIG['door_access_password']

      cardid = self.id.to_s.rjust(3, '0')
      cardperm = self.card_permissions.to_s.rjust(3, '0')
      cardnum = self.card_number.rjust(8, '0')

      # login and send the command all in one go (auto-logout is a feature of the arduino when used this way)
      source = open("#{door_access_url}?m#{cardid}&p#{cardperm}&t#{cardnum}&e=#{door_access_password}").read
      results = source.scan(/cur/)

      if(results.size > 0) then
        #only return true if we got some kind of decent response
        return true
      else
        # We didn't get a decent response.
        return false
      end
  end

  def self.upload_all_to_door
    @cards = Card.all
    @end_results = Array.new

    # load config values
    door_access_url = APP_CONFIG['door_access_url']
    door_access_password = APP_CONFIG['door_access_password']

    @cards.each do |u|
      cardid = u.id.to_s.rjust(3, '0')
      cardperm = u.card_permissions.to_s.rjust(3, '0')
      cardnum = u.card_number.rjust(8, '0')

      # login and send the command all in one go (auto-logout is a feature of the arduino when used this way)
      source = open("#{door_access_url}?m#{cardid}&p#{cardperm}&t#{cardnum}&e=#{door_access_password}").read
      results = source.scan(/cur/)

      if(results.size > 0) then
        #only return true if we got some kind of decent response
        @end_results.push([cardid,"OK"])
      else
        @end_results.push([cardid,"FAIL"])
      end
    end

    return @end_results
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  load_and_authorize_resource except: :authorize
  before_filter :authenticate_user!, except: :authorize
  
  # GET /cards
  # GET /cards.json
  def index
    #@cards = Card.all
    #authorize! :read, @cards
    @cards = @cards.sort_by{|e| e[:id]}

    if can? :read, DoorLog then
      most_active_count = 0
      runner_up_count = 0
      @most_active_card = nil
      @runner_up_card = nil
      @cards.each do |card|
        card_num_R = card.card_number.to_i(16)%32767
        card[:accesses_this_week] = DoorLog.where("key = ? AND data = ? AND created_at > ?", 'G', card_num_R, DateTime.now - 1.month).order("created_at DESC").group_by { |d| d.created_at.beginning_of_day }.count
      end
      @most_active_cards = @cards.sort{|a,b| b[:accesses_this_week] <=> a[:accesses_this_week]}
      @most_active_card = @most_active_cards[0]
      @runner_up_card = @most_active_cards[1]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    if can? :read, DoorLog then
      card_num_R = @card.card_number.to_i(16)%32767
      @door_logs = DoorLog.where('key = ? AND data = ?', "G", card_num_R).order("created_at DESC")
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @card }
    end
  end

  # PUT /cards/1/upload
  def upload
    #@card = Card.find(params[:id])
    @upload_result = @card.upload_to_door

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @upload_result }
    end
  end

  # PUT /cards/upload_all
  def upload_all
    @upload_result = Card.upload_all_to_door

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @upload_result }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    #@card = Card.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @card }
    end
  end

  # GET /cards/1/edit
  def edit
    #@card = Card.find(params[:id])
  end

  # POST /cards
  # POST /cards.json
  def create
    #@card = Card.new(params[:card])

    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_url, :notice => 'Card was successfully created.' }
        format.json { render :json => @card, :status => :created, :location => @card }
      else
        format.html { render :action => "new" }
        format.json { render :json => @card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    #@card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to cards_url, :notice => 'Card was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @card.errors, :status => :unprocessable_entity }
      end
    end
  end

  def authorize

    # Stop unless signed in already, OR if the supplied user/pass params are good.
    unless current_user || check_auth(params['user'],params['pass'])
      @auth = "bad_user_or_pass"
    else
      # Stop unless the user can access the door system
      unless can? :authorize, Card
        @auth = "bad_user_permissions"
        Rails.logger.warn "----------\r\nWARNING: CARD AUTH ATTEMPT DENIED. USER #{current_user.inspect}\r\n----------"
      else

        begin
          @card = Card.find(:first, :conditions => ["lower(card_number) = ?", params[:id].downcase])
          @auth = @card.inspect 
          if @card && @card.user 
            @auth = @card.user.has_certification?(params[:device])
          else
            @auth = false
          end
        rescue
          @auth = false
        end
      end
    end

    if @card && @card.user
      username = @card.user.name
    else
      username = nil
    end

    render json: [@auth, username]
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    #@card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url, :notice => 'Card successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @card.user_id = params[:user] if params[:user].present? %>
  <div class="field">
    <%= f.label :user %><br />
    <%= collection_select(:card, :user_id, User.all.sort_by(&:name), :id, :name, :include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :name, "Card Note" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :id, "Card DB ID" %><br />
    <%= f.number_field :id, :in => 10...201 %>
  </div>
  <div class="field">
    <%= f.label :card_number, "Card Number" %><br />
    <%= f.text_field :card_number %>
  </div>
  <div class="field">
    <%= f.label :card_permissions %><br />
    <%= f.select :card_permissions, [["Enabled",1],["Disabled",255]]  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Access Cards</h1>

<%= link_to 'New Card', new_card_path, :class => "btn" if can? :create, Card %>
<%= link_to 'Upload all cards', upload_all_path, :class => "btn" if can? :upload_all, Card %>
<%= link_to 'Door Logs', door_logs_path, :class => "btn" if can? :read, DoorLog %>
<%= link_to 'Space API', space_api_path, :class => "btn" %>
<%= link_to 'Remote Door Access', space_api_access_path, :class => "btn" if can? :access_doors_remotely, :door_access %>
<p>
<b>Most Active Card Last Month:</b> <%= @most_active_card.user.name unless @most_active_card.user.blank? %> (<%= @most_active_card.accesses_this_week unless @most_active_card.blank? %> days)
</p>
<p>
<% unless @runner_up_card.blank? || @runner_up_card.user.blank? %>
<b>Runner Up:</b> <%= @runner_up_card.user.name %> (<%= @runner_up_card.accesses_this_week %> days)
<% end %>
</p>

<table class="lined-table">
  <col />
  <col />
  <col class="col_highlight" />
  <col />
  <col class="col_highlight" />
  <tr>
    <th>User</th>
    <th>Note</th>
    <th>DB ID</th>
    <th>Card #</th>
    <th>Access?</th>
    <th>Days Accessed Last Month</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  
<% if !@cards.blank? %>
  <% @cards.each do |card| %>
  <tr>
    <td>
      <% if card.user.nil? %>
        n/a
      <% else %>
        <%= raw(card.user.member_status_symbol) %>
        <%= link_to card.user.name , card %>
      <% end %>
    </td>
    <td><%= card.name %></td>
    <td><%= card.id %></td>
    <td><%= card.card_number %></td>
    <td><%= if card.card_permissions == 1 then "Access" end %></td>
    <td><%= card.accesses_this_week unless card.accesses_this_week < 1 %></td>
    <td><%= link_to 'Upload', upload_path(card) if can? :upload, card %></td>
    <td><%= link_to 'Edit', edit_card_path(card) if can? :update, card %></td>
    <td><%= link_to 'Destroy', card, :confirm => 'Are you sure? WARNING: THIS DOES NOT REMOVE THE CARD FROM THE DOOR SYSTEM! DISABLE AND UPLOAD IT FIRST.', :method => :delete if can? :destroy, card %></td>
  </tr>
  <% end %>
<% end %>
</table>

<br />

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p>
  <b>User:</b>
  <%= link_to @card.user.name, @card.user unless @card.user.blank? %>
</p>

<p>
  <b>Card Note:</b>
  <%= @card.name %>
</p>

<p>
  <b>Card DB ID:</b>
  <%= @card.id %>
</p>

<p>
  <b>Card Number:</b>
  <%= @card.card_number %>
</p>

<p>
  <b>Card Permissions:</b>
  <%= if @card.card_permissions == 1 then "Enabled" else "Disabled" end %>
</p>

<% if can? :read, DoorLog %>
<p>
  <b>Access attempts:</b>
<ul>
<% @door_logs.each do |log| %>
  <li><%= log.created_at %></li>
<% end %>
</ul>
</p>
<% end %>

<%= link_to 'Upload to Door', upload_path(@card) if can? :upload, @card %>
<% if can? :update, @card then %><%= link_to 'Edit', edit_card_path(@card) %> |<% end %>
<%= link_to 'Back', cards_path %>

app/views/cards/upload.html.erb
<% if @upload_result %>
<p>
  <b>Upload result:</b>
  <%= @card.card_number %> uploaded successfully.
</p>
<% else %>
<p>
  <b>Upload result:</b>
  Error uploading <%= @card.card_number %>.
</p>
<% end %>

<%= link_to 'Back', cards_path %>

app/views/cards/upload_all.html.erb
<p>
<b>Upload results:</b>
<ul>
  <% @upload_result.each do |r| %>
    <li><%= r[0] %> <%= r[1] %></li>
  <% end %>
</ul>
</p>


<%= link_to 'Back', cards_path %>